### ISSUE TITLE
Filelinks from RTE input are not rendered correctly

### ISSUE THREAD

**Issue by ghost** [nitsan-technologies/ns_faq#1]
Filelinks for example are not correct rendered, when they are defined in RTE. Frontend-Output contains  t3://file?uid=xxx, i think this will happen with page-links as well.

Solution: Change Partial/FaqToggle.html and replace 
<f:format.raw>{faq.faqContent}</f:format.raw> with 
<f:format.html>{faq.faqContent}</f:format.html>

**Comment by nitsan-technologies** [comment]
Hello @OlafDoering 

First of all, thank you very much for using our extension, and sorry for the inconvenience.

Fyi, We have resolved this issue you can find the latest commit here https://github.com/nitsan-technologies/ns_faq/commit/f2da4447a23b508334447d101360d8a330925182

Thanks & Regards
